table aux_on_time
	excludeFromModelRefresh
	lineageTag: 1b6dae18-c0f8-4e0d-98d6-f63de562eba1

	column tempo
		dataType: string
		lineageTag: c7f81f94-49fa-4427-807e-b762769bf4d9
		summarizeBy: none
		sourceColumn: tempo
		sortByColumn: segundos

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column segundos
		dataType: int64
		formatString: 0
		lineageTag: 006184c7-df7e-4d65-835d-6838fe3c36ab
		summarizeBy: sum
		sourceColumn: segundos

		annotation SummarizationSetBy = Automatic

	partition aux_on_time = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("PcwxDoAwDEPRu2Tu4KYFcZeoOwywcH+Jgk2WSE+Rf4Q5bivz2ihh9TyuqZVyqurZxI3spHdyIRtUwp9SCxnTHLlXAFlQYn/1BcYD", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [tempo = _t, segundos = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"tempo", type text}, {"segundos", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

